# Generated by Django 2.1.7 on 2020-01-21 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EcommerceApp', '0003_auto_20200121_1413'),
        ('seller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.Products')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EcommerceApp.Profile')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together={('user', 'product')},
        ),
    ]
