# Generated by Django 2.1.7 on 2020-01-22 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0003_auto_20200121_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profileimage'),
        ),
    ]
