# Generated by Django 2.1.7 on 2020-01-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0004_auto_20200122_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='download.jpg', null=True, upload_to='profileimage'),
        ),
    ]
